import type { AppLocale } from "./config";

const he = {
  "nav.features":"יכולות","nav.how":"איך זה עובד","nav.audience":"למי זה מתאים","nav.plans":"מסלולים","nav.login":"כניסה","nav.trial":"חודש ראשון חינם",
  "hero.kicker":"עורך וידאו AI בעברית, בשיחה פשוטה","hero.line1":"עורך הווידאו","hero.line2":"שפשוט מדברים איתו","hero.copy":"מעלים וידאו ומספרים מה רוצים לקבל. Hypescript חותך, מסדר, מוסיף כתוביות, תמונות, מוזיקה ומיתוג — ואת כל השינויים רואים בזמן אמת.","hero.start":"התחלת חודש חינם","hero.see":"איך זה עובד","hero.trust":"נדרש כרטיס לאימות · אפשר לבטל לפני החיוב הראשון · מכסת ניסיון מוגנת",
  "features.eyebrow":"כלי העבודה שלך","features.title":"כל מה שצריך לעריכה, במקום אחד","features.copy":"עובדים בשיחה או בידיים, ורואים תמיד מה השתנה.",
  "how.eyebrow":"מתחילים בקלות","how.title":"מעלים, מבקשים וממשיכים משם","audience.eyebrow":"לכל סוג של תוכן","audience.title":"אותו עורך, לכל מה שרוצים ליצור",
  "pricing.eyebrow":"אפשר להתחיל בנחת","pricing.title":"מסלול שמתאים לקצב שלך","pricing.copy":"השימוש נעצר במכסה, כך שתמיד יודעים איפה עומדים.",
  "faq.eyebrow":"טוב לדעת","faq.title":"כמה תשובות לפני שמתחילים","final.eyebrow":"אפשר להתחיל עכשיו","final.line1":"מעלים חומר","final.line2":"ומתחילים ליצור","final.copy":"מתחילים בחודש ניסיון, מבקשים את העריכה שרוצים ורואים כל שינוי לפני שמפרסמים.","footer.privacy":"פרטיות","footer.terms":"תנאי שימוש","footer.refund":"ביטול והחזרים","footer.accessibility":"נגישות","footer.login":"כניסה",
} as const;
export type LandingMessageKey = keyof typeof he;
type Catalog = Record<LandingMessageKey,string>;

const en: Catalog = {
  "nav.features":"Features","nav.how":"How it works","nav.audience":"Who it is for","nav.plans":"Plans","nav.login":"Sign in","nav.trial":"First month free","hero.kicker":"An AI video editor you can simply talk to","hero.line1":"The video editor","hero.line2":"you simply talk to.","hero.copy":"Upload footage and describe the result: trim, organize, add captions, images, music and a logo, change format, or prepare social versions. Hypescript performs the work while every change stays visible and reviewable.","hero.start":"Start a free month","hero.see":"See how it works","hero.trust":"Card required for verification · Cancel before the first charge · Protected trial limits","features.eyebrow":"Real editing tools","features.title":"Everything needed to reach the final cut","features.copy":"Fewer windows, fewer exports and imports, fewer manual fixes.","how.eyebrow":"Easy to start","how.title":"From raw footage to a finished video in three steps","audience.eyebrow":"Built for real work","audience.title":"One tool, three creative workflows","pricing.eyebrow":"Start without risk","pricing.title":"A plan that fits your pace","pricing.copy":"Usage stops at the limit unless an active plan and explicit approval allow more.","faq.eyebrow":"Before you begin","faq.title":"Short questions, clear answers","final.eyebrow":"Your first video starts here","final.line1":"Upload. Ask.","final.line2":"Get a finished video.","final.copy":"Start with a trial month, talk to the video editor, and review every change before publishing.","footer.privacy":"Privacy","footer.terms":"Terms","footer.refund":"Refunds","footer.accessibility":"Accessibility","footer.login":"Sign in",
};
const ar: Catalog = {
  "nav.features":"الميزات","nav.how":"كيف يعمل","nav.audience":"لمن يناسب","nav.plans":"الخطط","nav.login":"تسجيل الدخول","nav.trial":"الشهر الأول مجانًا","hero.kicker":"محرر فيديو بالذكاء الاصطناعي تتحدث إليه ببساطة","hero.line1":"محرر الفيديو","hero.line2":"الذي تتحدث إليه.","hero.copy":"ارفع المواد الخام وصف النتيجة: قصّ، ترتيب، ترجمة، صور، موسيقى وشعار أو نسخة للشبكات. ينفّذ Hypescript العمل مع إبقاء كل تغيير ظاهرًا وقابلًا للمراجعة.","hero.start":"ابدأ شهرًا مجانيًا","hero.see":"شاهد كيف يعمل","hero.trust":"بطاقة مطلوبة للتحقق · يمكن الإلغاء قبل أول دفعة · حدود تجربة محمية","features.eyebrow":"أدوات تحرير حقيقية","features.title":"كل ما يلزم للوصول إلى النسخة النهائية","features.copy":"نوافذ أقل، تصدير واستيراد أقل، وإصلاحات يدوية أقل.","how.eyebrow":"بداية سهلة","how.title":"من المواد الخام إلى فيديو جاهز في ثلاث خطوات","audience.eyebrow":"مصمم للعمل الحقيقي","audience.title":"أداة واحدة لثلاثة أساليب إنتاج","pricing.eyebrow":"ابدأ بلا مخاطرة","pricing.title":"خطة تناسب وتيرتك","pricing.copy":"يتوقف الاستخدام عند الحد ما لم توجد خطة نشطة وموافقة صريحة.","faq.eyebrow":"قبل البدء","faq.title":"أسئلة قصيرة وإجابات واضحة","final.eyebrow":"فيديوك الأول يبدأ هنا","final.line1":"ارفع. اطلب.","final.line2":"احصل على فيديو جاهز.","final.copy":"ابدأ بشهر تجريبي، تحدث إلى محرر الفيديو وراجع كل تغيير قبل النشر.","footer.privacy":"الخصوصية","footer.terms":"الشروط","footer.refund":"الإلغاء والاسترداد","footer.accessibility":"إمكانية الوصول","footer.login":"تسجيل الدخول",
};
const ru: Catalog = {
  "nav.features":"Возможности","nav.how":"Как это работает","nav.audience":"Для кого","nav.plans":"Тарифы","nav.login":"Войти","nav.trial":"Первый месяц бесплатно","hero.kicker":"AI-видеоредактор, с которым можно просто говорить","hero.line1":"Видеоредактор,","hero.line2":"с которым говорят.","hero.copy":"Загрузите материал и опишите результат: сократить, упорядочить, добавить субтитры, изображения, музыку и логотип, сменить формат или сделать версии для соцсетей. Hypescript выполняет работу, а каждое изменение остаётся видимым и проверяемым.","hero.start":"Начать бесплатный месяц","hero.see":"Как это работает","hero.trust":"Карта нужна для проверки · Отмена до первого списания · Защищённые лимиты пробного периода","features.eyebrow":"Настоящие инструменты монтажа","features.title":"Всё для финальной версии","features.copy":"Меньше окон, экспорта, импорта и ручных исправлений.","how.eyebrow":"Легко начать","how.title":"От исходников до готового видео за три шага","audience.eyebrow":"Для реальной работы","audience.title":"Один инструмент, три темпа производства","pricing.eyebrow":"Без риска","pricing.title":"Тариф под ваш темп","pricing.copy":"Использование остановится на лимите без активного тарифа и явного разрешения.","faq.eyebrow":"Перед началом","faq.title":"Короткие вопросы, ясные ответы","final.eyebrow":"Первое видео начинается здесь","final.line1":"Загрузите. Попросите.","final.line2":"Получите готовое видео.","final.copy":"Начните с пробного месяца, общайтесь с редактором и проверяйте каждое изменение до публикации.","footer.privacy":"Конфиденциальность","footer.terms":"Условия","footer.refund":"Отмена и возврат","footer.accessibility":"Доступность","footer.login":"Войти",
};
const hi: Catalog = {
  "nav.features":"सुविधाएँ","nav.how":"यह कैसे काम करता है","nav.audience":"किसके लिए","nav.plans":"योजनाएँ","nav.login":"साइन इन","nav.trial":"पहला महीना मुफ़्त","hero.kicker":"AI वीडियो एडिटर जिससे आप बस बात कर सकते हैं","hero.line1":"वीडियो एडिटर","hero.line2":"जिससे आप बस बात करें।","hero.copy":"फ़ुटेज अपलोड करके नतीजा बताएँ: काटना, व्यवस्थित करना, कैप्शन, चित्र, संगीत और लोगो जोड़ना, फ़ॉर्मेट बदलना या सोशल संस्करण बनाना। Hypescript काम करता है और हर बदलाव दिखाई देता है व जाँचा जा सकता है।","hero.start":"मुफ़्त महीना शुरू करें","hero.see":"देखें कैसे काम करता है","hero.trust":"सत्यापन के लिए कार्ड आवश्यक · पहले शुल्क से पहले रद्द करें · सुरक्षित ट्रायल सीमा","features.eyebrow":"असल एडिटिंग टूल","features.title":"अंतिम वीडियो तक पहुँचने के लिए सब कुछ","features.copy":"कम विंडो, कम आयात-निर्यात और कम मैन्युअल सुधार।","how.eyebrow":"शुरू करना आसान","how.title":"कच्चे फ़ुटेज से तैयार वीडियो तक तीन चरण","audience.eyebrow":"असल काम के लिए बनाया गया","audience.title":"एक टूल, तीन रचनात्मक वर्कफ़्लो","pricing.eyebrow":"बिना जोखिम शुरू करें","pricing.title":"आपकी गति के अनुसार योजना","pricing.copy":"सक्रिय योजना और स्पष्ट अनुमति के बिना सीमा पर उपयोग रुक जाता है।","faq.eyebrow":"शुरू करने से पहले","faq.title":"छोटे सवाल, साफ़ जवाब","final.eyebrow":"आपका पहला वीडियो यहाँ शुरू होता है","final.line1":"अपलोड करें। बताएँ।","final.line2":"तैयार वीडियो पाएँ।","final.copy":"ट्रायल महीने से शुरू करें, वीडियो एडिटर से बात करें और प्रकाशित करने से पहले हर बदलाव देखें।","footer.privacy":"गोपनीयता","footer.terms":"शर्तें","footer.refund":"रद्दीकरण और रिफ़ंड","footer.accessibility":"पहुंच-योग्यता","footer.login":"साइन इन",
};

const freeEntry: Record<AppLocale, Pick<Catalog,"nav.trial"|"hero.start"|"hero.trust">> = {
  he:{"nav.trial":"התחל בחינם","hero.start":"התחל בחינם","hero.trust":"בלי כרטיס אשראי · בלי התחייבות · מתחילים לערוך בחינם"},
  en:{"nav.trial":"Start free","hero.start":"Start free","hero.trust":"No credit card · No commitment · Start editing for free"},
  ar:{"nav.trial":"ابدأ مجانًا","hero.start":"ابدأ مجانًا","hero.trust":"من دون بطاقة ائتمان · من دون التزام · ابدأ التحرير مجانًا"},
  ru:{"nav.trial":"Начать бесплатно","hero.start":"Начать бесплатно","hero.trust":"Без банковской карты · Без обязательств · Начните редактировать бесплатно"},
  hi:{"nav.trial":"मुफ़्त शुरू करें","hero.start":"मुफ़्त शुरू करें","hero.trust":"क्रेडिट कार्ड नहीं · कोई प्रतिबद्धता नहीं · मुफ़्त संपादन शुरू करें"},
};

export const LANDING_CATALOGS: Record<AppLocale,Catalog> = {
  he:{...he,...freeEntry.he}, en:{...en,...freeEntry.en}, ar:{...ar,...freeEntry.ar},
  ru:{...ru,...freeEntry.ru}, hi:{...hi,...freeEntry.hi},
};
